<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="ZXing.Net" />
    <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BarcodeGenerator.Entities\BarcodeGenerator.Entities.csproj" />
  </ItemGroup>

</Project>
