// ***********************************************************************
// Assembly          : BarcodeGenerator.Configuration
// Author            : Robert Eberhart
// Created           : 09-11-2026
// ***********************************************************************
namespace BarcodeGenerator.Configuration;

/// <summary>
/// Represents the configuration options for generating reports in the BarcodeGenerator application.
/// </summary>
/// <remarks>
/// This class provides properties to specify metadata such as the author and company associated with the report.
/// </remarks>
public sealed class ReportConfigurationOptions {
    /// <summary>
    /// Gets or sets the author of the report.
    /// </summary>
    /// <value>
    /// A <see cref="string"/> representing the name of the author associated with the report.
    /// </value>
    /// <remarks>
    /// This property is used to specify the individual or entity responsible for creating the report.
    /// </remarks>
    public string Author { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the name of the company associated with the report.
    /// </summary>
    /// <value>
    /// A <see cref="string"/> representing the company name.
    /// </value>
    /// <remarks>
    /// This property is used to specify the company metadata for reports generated by the BarcodeGenerator application.
    /// </remarks>
    public string Company { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the subject of the report.
    /// </summary>
    /// <value>
    /// A <see cref="string"/> representing the subject of the report.
    /// </value>
    /// <remarks>
    /// This property allows specifying a brief description or title for the report.
    /// </remarks>
    public string Subject { get; set; } = string.Empty;
}